# Generated by Django 3.0.1 on 2020-03-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('Item_photo', models.ImageField(upload_to='')),
                ('item_price', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Item Details',
            },
        ),
        migrations.CreateModel(
            name='ItemOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xanku.ItemDetail')),
            ],
            options={
                'verbose_name_plural': 'Course Book',
            },
        ),
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_country', models.CharField(max_length=10)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xanku.ItemDetail')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xanku.ItemOwner')),
            ],
            options={
                'verbose_name_plural': 'Examination Date',
            },
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xanku.ItemDetail')),
            ],
            options={
                'verbose_name_plural': 'Item Description',
            },
        ),
    ]
