# Generated by Django 3.0.1 on 2020-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xanku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemowner',
            options={'verbose_name_plural': 'Owner Detail'},
        ),
        migrations.AlterModelOptions(
            name='ownercontact',
            options={'verbose_name_plural': 'Owner Contact'},
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='Item_photo',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
