# Generated by Django 3.0.1 on 2020-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xanku', '0002_auto_20200321_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemowner',
            old_name='name',
            new_name='item_name',
        ),
    ]
