# Generated by Django 3.0.1 on 2020-03-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=20)),
                ('product_price', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Prodtuct Details',
            },
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_owner', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductDetail')),
            ],
            options={
                'verbose_name_plural': 'Owner Detail',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductDetail')),
            ],
            options={
                'verbose_name_plural': 'Product Description',
            },
        ),
        migrations.CreateModel(
            name='OwnerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_country', models.CharField(max_length=10)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductOwner')),
            ],
            options={
                'verbose_name_plural': 'Owner Contact',
            },
        ),
    ]
