# Generated by Django 3.0.4 on 2020-04-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name_plural': 'Product Details'},
        ),
        migrations.AddField(
            model_name='ownercontact',
            name='product_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductOwner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownercontact',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductDetail'),
        ),
    ]
